# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.lims_required import LimsRequired

class TestLimsRequired(unittest.TestCase):
    """LimsRequired unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimsRequired(self):
        """Test LimsRequired"""
        # inst = LimsRequired()

if __name__ == '__main__':
    unittest.main()
