# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.inj2_type import Inj2Type

class TestInj2Type(unittest.TestCase):
    """Inj2Type unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInj2Type(self):
        """Test Inj2Type"""
        # inst = Inj2Type()

if __name__ == '__main__':
    unittest.main()
