# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.inj2_retsetting import Inj2Retsetting

class TestInj2Retsetting(unittest.TestCase):
    """Inj2Retsetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInj2Retsetting(self):
        """Test Inj2Retsetting"""
        # inst = Inj2Retsetting()

if __name__ == '__main__':
    unittest.main()
